### ISSUE TITLE
Deadlock if webdriver download fails

### ISSUE THREAD

**Issue by divinaet** [AxaFrance/webengine-dotnet#48]
During the installation of a new driver, a directory is created.

If the download fails (network error etc.), the directory is not deleted. This is a problem because during the test run, the framework thinks the correct version is installed but the driver launch fails (exe not found) and it does not try to re-download it.

Advice: Do not leave a directory with an expected name if the download is not successful.

**Comment by huaxing-yuan** [comment]
Tested OK
